// @generated by protoc-gen-connect-es v0.13.0 with parameter "target=ts"
// @generated from file cache.proto (package nrwl.grpc, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MethodKind } from '@bufbuild/protobuf';
import {
  RestoreRequest,
  RestoreResponse,
  StoreRequest,
  StoreResponse,
} from './cache_pb.js';

/**
 * @generated from service nrwl.grpc.CacheService
 */
export const CacheService = {
  typeName: 'nrwl.grpc.CacheService',
  methods: {
    /**
     * @generated from rpc nrwl.grpc.CacheService.Restore
     */
    restore: {
      name: 'Restore',
      I: RestoreRequest,
      O: RestoreResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc nrwl.grpc.CacheService.Store
     */
    store: {
      name: 'Store',
      I: StoreRequest,
      O: StoreResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc nrwl.grpc.CacheService.StoreV2
     */
    storeV2: {
      name: 'StoreV2',
      I: StoreRequest,
      O: StoreResponse,
      kind: MethodKind.Unary,
    },
  },
} as const;
